### ISSUE TITLE
do we want to modify @/suggestion dropdown style?

### ISSUE THREAD

**Issue by YoshiyukiSakura** [opensquare-network/rich-text-editor#19]
it looks this way right now, and we fully capable to modify basically anything
<img width="949" alt="image" src="https://user-images.githubusercontent.com/12393771/169478846-d0dc5daa-cb51-48d3-8223-d0900721f496.png">

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=10110%3A45426)

Preview
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/169497203-47d05e3a-828d-439d-8322-58cf8a455e5b.png">
