### ISSUE TITLE
Fix the tab style on mobile size

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/rich-text-editor#29]
Current status:
![ytirO40k8F](https://user-images.githubusercontent.com/2264908/170640601-3f8f9974-fe26-437c-8e0f-441769a07f46.png)

Correct design [figma](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=2060%3A11145):
![Xe3YMXhLCY](https://user-images.githubusercontent.com/2264908/170641001-be43f7d5-cfc7-47f8-9038-3d2f6a28591d.png)

**Comment by 2nthony** [comment]
#16
