### ISSUE TITLE
Enlarge height by clicking enter

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/rich-text-editor#31]
Given max height as `x`,
- [ ] If user set the height manually, keep the height
- [ ] If no user setting, we should enlarge the height after enter clicked, the enlarged height should be one row height
- [ ] If the `now height` >= `x`, enlarge by enter won't work; 
- [ ] If the `now height` >= `x`, the height should be reduced after user clicked the `reduce` key

**Comment by YoshiyukiSakura** [comment]
actually we will need to give a `min height` via props, so when we reduce text contents , the editor knows if it should shrink height

`max-height` can be set in css

- [ ] If user set the height manually (available range: minHeight ~ maxHeight), keep the height, also 
- [ ] If no user setting, we should enlarge the height after enter clicked, by line-height
- [ ] If the `now height` >= `maxHeight`,  show a scroll bar
- [ ] If the `now height` < `x`, the height should be reduced after user pressed the `reduce` key
